# Generated by Django 3.2.7 on 2021-09-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_bid',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
