# Generated by Django 3.2.7 on 2021-09-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='alert_percent',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='setting',
            name='total_reserved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
