# Generated by Django 3.2.7 on 2021-09-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_auto_20210924_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='total_reserved',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
